const recordAllList = [
  {
    "id": 15590,
    "inspectMaterialId": 477,
    "inspectMaterialNumId": 474,
    "itemId": 1,
    "inspectionSwicth": 1,
    "itemName": "123",
    "verificationBasis": null,
    "verificationInstrument": null,
    "verificationInstrumentName": null,
    "verificationMethod": null,
    "remark": null,
    "itemGroupName": "测试",
    "analyzeMethod": "quantitative",
    "analyzeMethodName": "定量分析",
    "checkResult": null,
    "singleConclusion": null,
    "reviewResult": null,
    "reviewConclusion": null,
    "authorizeResult": null,
    "authorizeConclusion": null,
    "importantInspection": 0,
    "required": 1,
    "recordInspectionValue": 1,
    "defaultQualified": false,
    "defectLevel": null,
    "defectLevelName": null,
    "minQuality": null,
    "actualQuality": 0,
    "unqualifiedQuantity": 1,
    "samplePlanId": 1,
    "samplePlanName": "全抽",
    "inspectStandard": "10.00±5.00",
    "inspectLevel": "",
    "stringency": null,
    "stringencyName": null,
    "aqlValue": "",
    "samplingQuantity": 0,
    "inspectValue": null,
    "comparator": "between",
    "referenceValue": "10",
    "upperLimitValue": "15",
    "downLimitValue": "5",
    "inspectionCondition": null,
    "upperTolerance": null,
    "lowerTolerance": null,
    "unit": null,
    "inputMode": "handInput",
    "optionalValue": null,
    "defaultValue": null,
    "itemOptionList": null,
    "itemExecuteFileList": null,
    "itemDefectFileList": null,
    "itemGuidanceFileList": null,
    "fileUrls": null,
    "acceptValue": 0,
    "refuseValue": 0,
    "sampleType": "full",
    "itemValues": [//有三个，样本检测值，样本码，样本标识
      {
        "id": 47,
        "numItemId": 15590,
        "productCode": "样本码1",
        "inspectValue": "1",
        "checkConclusion": "1",
        "reviewValue": null,
        "reviewConclusion": null,
        "authorizeValue": null,
        "authorizeConclusion": null,
        "sampleIdentification": "样本标识1"
      },
      {
        "id": 48,
        "numItemId": 15590,
        "productCode": "样本码2",
        "inspectValue": "2",
        "checkConclusion": "0",
        "reviewValue": null,
        "reviewConclusion": null,
        "authorizeValue": null,
        "authorizeConclusion": null,
        "sampleIdentification": "样本标识2"
      }
    ],
    "itemDefects": null
  },
  {
    "id": 15591,
    "inspectMaterialId": 477,
    "inspectMaterialNumId": 474,
    "itemId": 136,
    "inspectionSwicth": null,
    "itemName": "4005唱盘测试",
    "verificationBasis": "君兰质量",
    "verificationInstrument": null,
    "verificationInstrumentName": null,
    "verificationMethod": "目测",
    "remark": null,
    "itemGroupName": "唱盘测试",
    "analyzeMethod": "manual",
    "analyzeMethodName": "人工分析",
    "checkResult": "",
    "singleConclusion": null,
    "reviewResult": null,
    "reviewConclusion": null,
    "authorizeResult": null,
    "authorizeConclusion": null,
    "importantInspection": 0,
    "required": 1,
    "recordInspectionValue": 1,
    "defaultQualified": true,
    "defectLevel": null,
    "defectLevelName": null,
    "minQuality": null,
    "actualQuality": null,
    "unqualifiedQuantity": null,
    "samplePlanId": null,
    "samplePlanName": null,
    "inspectStandard": null,
    "inspectLevel": null,
    "stringency": null,
    "stringencyName": null,
    "aqlValue": null,
    "samplingQuantity": 0,
    "inspectValue": null,
    "comparator": null,
    "referenceValue": null,
    "upperLimitValue": null,
    "downLimitValue": null,
    "inspectionCondition": null,
    "upperTolerance": null,
    "lowerTolerance": null,
    "unit": null,
    "inputMode": "multipleChoice",
    "optionalValue": "33/45/78 3K转速2990-3040HZ,33/45/78转抖摆<=0.35%,报数17-23范围为正常,第六首/第七首左右声道分音",
    "defaultValue": "33/45/78 3K转速2990-3040HZ,33/45/78转抖摆<=0.35%,报数17-24范围为正常,第六首/第七首左右声道分音",
    "itemOptionList": null,
    "itemExecuteFileList": null,
    "itemDefectFileList": null,
    "itemGuidanceFileList": null,
    "fileUrls": null,
    "acceptValue": 0,
    "refuseValue": 0,
    "sampleType": null,
    "itemValues": [//有2个，样本检测值，样本码
      {
        "id": 42,
        "numItemId": 15591,
        "productCode": "11",
        "inspectValue": "",
        "checkConclusion": "1",
        "reviewValue": null,
        "reviewConclusion": null,
        "authorizeValue": null,
        "authorizeConclusion": null
      }
    ],
    "itemDefects": null
  },
  {
    "id": 15592,
    "inspectMaterialId": 477,
    "inspectMaterialNumId": 474,
    "itemId": 124,
    "inspectionSwicth": null,
    "itemName": "AM状态主机面板功能按键操作测试",
    "verificationBasis": "君兰质量",
    "verificationInstrument": null,
    "verificationInstrumentName": null,
    "verificationMethod": "目测",
    "remark": null,
    "itemGroupName": "AM测试",
    "analyzeMethod": "manual",
    "analyzeMethodName": "人工分析",
    "checkResult": "",
    "singleConclusion": null,
    "reviewResult": null,
    "reviewConclusion": null,
    "authorizeResult": null,
    "authorizeConclusion": null,
    "importantInspection": 0,
    "required": 1,
    "recordInspectionValue": 1,
    "defaultQualified": true,
    "defectLevel": null,
    "defectLevelName": null,
    "minQuality": null,
    "actualQuality": null,
    "unqualifiedQuantity": null,
    "samplePlanId": null,
    "samplePlanName": null,
    "inspectStandard": null,
    "inspectLevel": null,
    "stringency": null,
    "stringencyName": null,
    "aqlValue": null,
    "samplingQuantity": 0,
    "inspectValue": null,
    "comparator": null,
    "referenceValue": null,
    "upperLimitValue": null,
    "downLimitValue": null,
    "inspectionCondition": null,
    "upperTolerance": null,
    "lowerTolerance": null,
    "unit": null,
    "inputMode": "multipleChoice",
    "optionalValue": "VOL+/-,旋钮选台播放",
    "defaultValue": "VOL+/-,旋钮选台播放",
    "itemOptionList": null,
    "itemExecuteFileList": null,
    "itemDefectFileList": null,
    "itemGuidanceFileList": null,
    "fileUrls": null,
    "acceptValue": 0,
    "refuseValue": 0,
    "sampleType": null,
    "itemValues": [//有2个，样本检测值，样本标识
      {
        "id": 43,
        "numItemId": 15592,
        "inspectValue": "",
        "checkConclusion": "1",
        "reviewValue": null,
        "reviewConclusion": null,
        "authorizeValue": null,
        "authorizeConclusion": null,
        "sampleIdentification": "标识1"
      }
    ],
    "itemDefects": null
  },
  {
    "id": 15593,
    "inspectMaterialId": 477,
    "inspectMaterialNumId": 474,
    "itemId": 123,
    "inspectionSwicth": null,
    "itemName": "AM频率范围",
    "verificationBasis": "君兰质量",
    "verificationInstrument": null,
    "verificationInstrumentName": null,
    "verificationMethod": "目测",
    "remark": null,
    "itemGroupName": "AM测试",
    "analyzeMethod": "manual",
    "analyzeMethodName": "人工分析",
    "checkResult": null,
    "singleConclusion": null,
    "reviewResult": null,
    "reviewConclusion": null,
    "authorizeResult": null,
    "authorizeConclusion": null,
    "importantInspection": 0,
    "required": 1,
    "recordInspectionValue": 1,
    "defaultQualified": true,
    "defectLevel": null,
    "defectLevelName": null,
    "minQuality": null,
    "actualQuality": null,
    "unqualifiedQuantity": null,
    "samplePlanId": null,
    "samplePlanName": null,
    "inspectStandard": null,
    "inspectLevel": null,
    "stringency": null,
    "stringencyName": null,
    "aqlValue": null,
    "samplingQuantity": 0,
    "inspectValue": null,
    "comparator": null,
    "referenceValue": null,
    "upperLimitValue": null,
    "downLimitValue": null,
    "inspectionCondition": null,
    "upperTolerance": null,
    "lowerTolerance": null,
    "unit": null,
    "inputMode": "singleChoice",
    "optionalValue": "530-1710KHz,其他",
    "defaultValue": null,
    "itemOptionList": null,
    "itemExecuteFileList": null,
    "itemDefectFileList": null,
    "itemGuidanceFileList": null,
    "fileUrls": null,
    "acceptValue": 0,
    "refuseValue": 0,
    "sampleType": null,
    "itemValues": [//有1个，样本检测值
      {
        "id": 44,
        "numItemId": 15593,
        "inspectValue": null,
        "checkConclusion": "1",
        "reviewValue": null,
        "reviewConclusion": null,
        "authorizeValue": null,
        "authorizeConclusion": null,
      },
      {
        "id": 45,
        "numItemId": 15593,
        "inspectValue": null,
        "checkConclusion": "0",
        "reviewValue": null,
        "reviewConclusion": null,
        "authorizeValue": null,
        "authorizeConclusion": null
      },
      {
        "id": 46,
        "numItemId": 15593,
        "inspectValue": null,
        "checkConclusion": "1",
        "reviewValue": null,
        "reviewConclusion": null,
        "authorizeValue": null,
        "authorizeConclusion": null,
      }
    ],
    "itemDefects": null
  }
]

const recordItem = {
  "id": null,
  "inspectMaterialId": 477,
  "inspectMaterialNumId": 474,
  "itemId": 1,
  "inspectionSwicth": 1,
  "itemName": "123",
  "verificationBasis": null,
  "verificationInstrument": null,
  "verificationInstrumentName": null,
  "verificationMethod": null,
  "remark": null,
  "itemGroupName": "测试",
  "analyzeMethod": "quantitative",
  "analyzeMethodName": "定量分析",
  "checkResult": null,
  "singleConclusion": null,
  "reviewResult": null,
  "reviewConclusion": null,
  "authorizeResult": null,
  "authorizeConclusion": null,
  "importantInspection": 0,
  "required": 1,
  "recordInspectionValue": 1,
  "defaultQualified": false,
  "defectLevel": null,
  "defectLevelName": null,
  "minQuality": null,
  "actualQuality": 0,
  "unqualifiedQuantity": 1,
  "samplePlanId": 1,
  "samplePlanName": "全抽",
  "inspectStandard": "10.00±5.00",
  "inspectLevel": "",
  "stringency": null,
  "stringencyName": null,
  "aqlValue": "",
  "samplingQuantity": 0,
  "inspectValue": null,
  "comparator": "between",
  "referenceValue": "10",
  "upperLimitValue": "15",
  "downLimitValue": "5",
  "inspectionCondition": null,
  "upperTolerance": null,
  "lowerTolerance": null,
  "unit": null,
  "inputMode": "handInput",
  "optionalValue": null,
  "defaultValue": null,
  "itemOptionList": null,
  "itemExecuteFileList": null,
  "itemDefectFileList": null,
  "itemGuidanceFileList": null,
  "fileUrls": null,
  "acceptValue": 0,
  "refuseValue": 0,
  "sampleType": "full",
  "itemValues": [//有三个，样本检测值，样本码，样本标识
    {
      "id": 47,
      "numItemId": null,
      "productCode": "样本码1",
      "inspectValue": "1",
      "checkConclusion": "1",
      "reviewValue": null,
      "reviewConclusion": null,
      "authorizeValue": null,
      "authorizeConclusion": null,
      "sampleIdentification": "样本标识1"
    },
    {
      "id": 48,
      "numItemId": null,
      "productCode": "样本码2",
      "inspectValue": "2",
      "checkConclusion": "0",
      "reviewValue": null,
      "reviewConclusion": null,
      "authorizeValue": null,
      "authorizeConclusion": null,
      "sampleIdentification": "样本标识2"
    }
  ],
  "itemDefects": null
}

function generateRecordItem() {
  const newRecordItem = JSON.parse(JSON.stringify(recordItem))
  const id = Math.floor(Math.random() * 10000) + 1;
  newRecordItem.id = id;
  newRecordItem.itemValues.forEach(item => {
    item.numItemId = id;
  })
  return newRecordItem;
}

export async function getRecordAllList() {
  const newRecordItem = generateRecordItem();
  const newRecordAllList = [...recordAllList, newRecordItem]
  console.log('获取所有记录', newRecordAllList);
  return newRecordAllList;
}

export async function addRecordItem() {
  const newRecordItem = generateRecordItem();
  console.log('新增记录', newRecordItem);
  return newRecordItem;
}